# Generated by Django 4.2 on 2023-04-27 14:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_comment_options_alter_comment_author_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='date',
            field=models.DateTimeField(db_index=True, default=datetime.datetime(2023, 4, 27, 17, 59, 7, 72617), verbose_name='Дата добавления'),
        ),
    ]
