# Generated by Django 4.2 on 2023-05-01 08:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_comment_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='date',
            field=models.DateTimeField(db_index=True, default=datetime.datetime(2023, 5, 1, 11, 24, 30, 991710), verbose_name='Дата добавления'),
        ),
    ]
