# Generated by Django 4.2 on 2023-05-01 09:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_blog_description_alter_blog_creation_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='creation_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 5, 1, 12, 47, 18, 132846), verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='blog',
            name='date_of_change',
            field=models.DateTimeField(auto_now=True, verbose_name='Дата редактирования'),
        ),
        migrations.AlterField(
            model_name='blog',
            name='description',
            field=models.CharField(max_length=255, verbose_name='Краткое описание'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='date',
            field=models.DateTimeField(db_index=True, default=datetime.datetime(2023, 5, 1, 12, 47, 18, 139845), verbose_name='Дата добавления'),
        ),
    ]
